export const PERMISSIONS = {
  TENANT_READ: "tenant.read",
  TENANT_UPDATE: "tenant.update",
  BRANCH_READ: "branch.read",
  BRANCH_UPDATE: "branch.update",
  MENU_READ: "menu.read",
  MENU_WRITE: "menu.write",
  CATEGORY_READ: "category.read",
  CATEGORY_WRITE: "category.write",
  PRODUCT_READ: "product.read",
  PRODUCT_WRITE: "product.write",
  ORDER_READ: "order.read",
  ORDER_WRITE: "order.write",
  CASHIER_PAYMENT: "cashier.payment",
  REPORT_VIEW: "report.view",
  USER_INVITE: "user.invite",
  ROLE_MANAGE: "role.manage",
  PERMISSION_MANAGE: "permission.manage",
  MEDIA_UPLOAD: "media.upload",
  MEDIA_MANAGE: "media.manage",
  THEME_UPDATE: "theme.update",
  STOREFRONT_PUBLISH: "storefront.publish",
  QR_GENERATE: "qr.generate",
  ADMIN_DASHBOARD_READ: "admin.dashboard.read",
  ADMIN_TENANT_READ: "admin.tenant.read",
  ADMIN_TENANT_CREATE: "admin.tenant.create",
  ADMIN_TENANT_UPDATE: "admin.tenant.update",
  ADMIN_USER_READ: "admin.user.read",
  ADMIN_USER_UPDATE: "admin.user.update",
  ADMIN_SESSION_REVOKE: "admin.session.revoke",
  ADMIN_AUDIT_READ: "admin.audit.read",
  ADMIN_SYSTEM_READ: "admin.system.read",
  BUSINESS_DASHBOARD_READ: "business.dashboard.read",
  BRANCH_CREATE: "branch.create",
  USER_READ: "user.read",
  USER_CREATE: "user.create",
  USER_UPDATE: "user.update",
  USER_SESSION_REVOKE: "user.session.revoke",
  USER_PASSWORD_RESET: "user.password.reset",
  BUSINESS_ACTIVITY_READ: "business.activity.read",
  BUSINESS_SETTINGS_READ: "business.settings.read",
  BUSINESS_SETTINGS_UPDATE: "business.settings.update",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_VALUES: PermissionCode[] = Object.values(PERMISSIONS);

export const PERMISSION_GROUPS: Record<PermissionCode, string> = {
  [PERMISSIONS.TENANT_READ]: "tenant",
  [PERMISSIONS.TENANT_UPDATE]: "tenant",
  [PERMISSIONS.BRANCH_READ]: "branch",
  [PERMISSIONS.BRANCH_UPDATE]: "branch",
  [PERMISSIONS.MENU_READ]: "menu",
  [PERMISSIONS.MENU_WRITE]: "menu",
  [PERMISSIONS.CATEGORY_READ]: "category",
  [PERMISSIONS.CATEGORY_WRITE]: "category",
  [PERMISSIONS.PRODUCT_READ]: "product",
  [PERMISSIONS.PRODUCT_WRITE]: "product",
  [PERMISSIONS.ORDER_READ]: "order",
  [PERMISSIONS.ORDER_WRITE]: "order",
  [PERMISSIONS.CASHIER_PAYMENT]: "cashier",
  [PERMISSIONS.REPORT_VIEW]: "report",
  [PERMISSIONS.USER_INVITE]: "user",
  [PERMISSIONS.ROLE_MANAGE]: "role",
  [PERMISSIONS.PERMISSION_MANAGE]: "permission",
  [PERMISSIONS.MEDIA_UPLOAD]: "media",
  [PERMISSIONS.MEDIA_MANAGE]: "media",
  [PERMISSIONS.THEME_UPDATE]: "theme",
  [PERMISSIONS.STOREFRONT_PUBLISH]: "storefront",
  [PERMISSIONS.QR_GENERATE]: "qr",
  [PERMISSIONS.ADMIN_DASHBOARD_READ]: "admin",
  [PERMISSIONS.ADMIN_TENANT_READ]: "admin",
  [PERMISSIONS.ADMIN_TENANT_CREATE]: "admin",
  [PERMISSIONS.ADMIN_TENANT_UPDATE]: "admin",
  [PERMISSIONS.ADMIN_USER_READ]: "admin",
  [PERMISSIONS.ADMIN_USER_UPDATE]: "admin",
  [PERMISSIONS.ADMIN_SESSION_REVOKE]: "admin",
  [PERMISSIONS.ADMIN_AUDIT_READ]: "admin",
  [PERMISSIONS.ADMIN_SYSTEM_READ]: "admin",
  [PERMISSIONS.BUSINESS_DASHBOARD_READ]: "business",
  [PERMISSIONS.BRANCH_CREATE]: "branch",
  [PERMISSIONS.USER_READ]: "user",
  [PERMISSIONS.USER_CREATE]: "user",
  [PERMISSIONS.USER_UPDATE]: "user",
  [PERMISSIONS.USER_SESSION_REVOKE]: "user",
  [PERMISSIONS.USER_PASSWORD_RESET]: "user",
  [PERMISSIONS.BUSINESS_ACTIVITY_READ]: "business",
  [PERMISSIONS.BUSINESS_SETTINGS_READ]: "business",
  [PERMISSIONS.BUSINESS_SETTINGS_UPDATE]: "business",
};
