import { PERMISSIONS } from "./permissions";
import type { PermissionCode } from "./permissions";
import { ROLES } from "./roles";
import type { Role } from "./roles";

// Single source of truth for what each system role can do. Consumed by the
// Prisma seed script (writes role_permissions rows) and available to the
// frontend for non-authoritative UI show/hide - the real enforcement point
// is always the API's PermissionsGuard, which reads role_permissions from
// the database, not this constant.
export const ROLE_PERMISSIONS: Record<Role, PermissionCode[]> = {
  [ROLES.SUPER_ADMIN]: [
    PERMISSIONS.TENANT_READ,
    PERMISSIONS.TENANT_UPDATE,
    PERMISSIONS.BRANCH_READ,
    PERMISSIONS.BRANCH_UPDATE,
    PERMISSIONS.MENU_READ,
    PERMISSIONS.MENU_WRITE,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.PRODUCT_WRITE,
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.ORDER_WRITE,
    PERMISSIONS.CASHIER_PAYMENT,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.USER_INVITE,
    PERMISSIONS.ROLE_MANAGE,
    PERMISSIONS.PERMISSION_MANAGE,
  ],
  [ROLES.TENANT_OWNER]: [
    PERMISSIONS.TENANT_READ,
    PERMISSIONS.TENANT_UPDATE,
    PERMISSIONS.BRANCH_READ,
    PERMISSIONS.BRANCH_UPDATE,
    PERMISSIONS.MENU_READ,
    PERMISSIONS.MENU_WRITE,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.PRODUCT_WRITE,
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.ORDER_WRITE,
    PERMISSIONS.CASHIER_PAYMENT,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.USER_INVITE,
    PERMISSIONS.ROLE_MANAGE,
  ],
  [ROLES.BRANCH_MANAGER]: [
    PERMISSIONS.BRANCH_READ,
    PERMISSIONS.BRANCH_UPDATE,
    PERMISSIONS.MENU_READ,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.ORDER_WRITE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.USER_INVITE,
  ],
  [ROLES.MENU_EDITOR]: [
    PERMISSIONS.MENU_READ,
    PERMISSIONS.MENU_WRITE,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.PRODUCT_WRITE,
  ],
  [ROLES.CASHIER]: [PERMISSIONS.ORDER_READ, PERMISSIONS.CASHIER_PAYMENT],
  [ROLES.WAITER]: [PERMISSIONS.ORDER_READ, PERMISSIONS.ORDER_WRITE],
  [ROLES.KITCHEN]: [PERMISSIONS.ORDER_READ],
};
