// Centralized path constants so route strings aren't scattered/duplicated
// across nav configs, links, and redirects.
export const ROUTES = {
  home: "/",
  login: "/login",
  forgotPassword: "/forgot-password",
  health: "/health",
  admin: "/admin",
  adminTenants: "/admin/tenants",
  adminNewTenant: "/admin/tenants/new",
  adminUsers: "/admin/users",
  adminAuditLogs: "/admin/audit-logs",
  adminSystem: "/admin/system",
  adminSupport: "/admin/support",
  business: "/business",
  businessProfile: "/business/profile",
  businessBranches: "/business/branches",
  businessNewBranch: "/business/branches/new",
  businessUsers: "/business/users",
  businessNewUser: "/business/users/new",
  businessActivity: "/business/activity",
  businessSettings: "/business/settings",
  businessMedia: "/business/media",
  businessMenus: "/business/menus",
  businessCategories: "/business/categories",
  businessProducts: "/business/products",
  businessStorefront: "/business/storefront",
  businessSearch: "/business/search",
  waiter: "/waiter",
  cashier: "/cashier",
  kitchen: "/kitchen",
  unauthorized: "/401",
  forbidden: "/403",
} as const;
