"use client";

import type { StorefrontQrSettings } from "@qr-platform/shared";
import {
  Button,
  Label,
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
  Switch,
} from "@qr-platform/ui";
import { useState } from "react";

import { qrCodeUrl } from "@/services/qr.service";

export interface QrCodePanelProps {
  qr: StorefrontQrSettings;
  onChange: (patch: Partial<StorefrontQrSettings>) => void;
}

const ERROR_CORRECTION_OPTIONS: Array<{ value: StorefrontQrSettings["errorCorrectionLevel"]; label: string }> = [
  { value: "L", label: "Düşük (L) - en yoğun veri" },
  { value: "M", label: "Orta (M)" },
  { value: "Q", label: "Yüksek (Q) - önerilen" },
  { value: "H", label: "En Yüksek (H) - logo için ideal" },
];

// Renders the *current draft* settings via the real backend QR endpoint
// (no client-side QR rendering logic duplicated) - so the small preview
// here and the downloaded file are always pixel-identical, generated by
// the exact same code path.
export function QrCodePanel({ qr, onChange }: QrCodePanelProps) {
  const [previewNonce, setPreviewNonce] = useState(0);
  const previewUrl = `${qrCodeUrl({ format: "png", errorCorrectionLevel: qr.errorCorrectionLevel, includeLogo: qr.includeLogo }, false)}&_=${previewNonce}`;

  const refreshPreview = (): void => setPreviewNonce((n) => n + 1);

  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-col gap-2">
        <Label>Hata Düzeltme Seviyesi</Label>
        <Select
          value={qr.errorCorrectionLevel}
          onValueChange={(value) => {
            onChange({ errorCorrectionLevel: value as StorefrontQrSettings["errorCorrectionLevel"] });
            refreshPreview();
          }}
        >
          <SelectTrigger>
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {ERROR_CORRECTION_OPTIONS.map((option) => (
              <SelectItem key={option.value} value={option.value}>
                {option.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      <div className="flex items-center justify-between gap-2 rounded-md border border-border p-3">
        <Label htmlFor="qr-include-logo" className="cursor-pointer font-normal">
          QR içine logo ekle
        </Label>
        <Switch
          id="qr-include-logo"
          checked={qr.includeLogo}
          onCheckedChange={(checked) => {
            onChange({ includeLogo: checked });
            refreshPreview();
          }}
        />
      </div>

      <div className="flex flex-col items-center gap-3 rounded-md border border-border p-4">
        <img src={previewUrl} alt="QR kod önizlemesi" width={200} height={200} className="rounded" />
        <div className="flex gap-2">
          <Button asChild variant="outline">
            <a href={qrCodeUrl({ format: "png", errorCorrectionLevel: qr.errorCorrectionLevel, includeLogo: qr.includeLogo }, true)}>
              PNG İndir
            </a>
          </Button>
          <Button asChild variant="outline">
            <a href={qrCodeUrl({ format: "svg", errorCorrectionLevel: qr.errorCorrectionLevel, includeLogo: qr.includeLogo }, true)}>
              SVG İndir
            </a>
          </Button>
        </div>
      </div>
    </div>
  );
}
